from django.urls import path
from . import bi_views, views

app_name = "dunnhumby_site"

urlpatterns = [
    # Authentication
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    # Main pages
    path("", views.site_index, name="index"),
    path("basket-analysis/", views.basket_analysis, name="basket_analysis"),
    path("association-rules/", views.association_rules, name="association_rules"),
    path("customer-segments/", views.customer_segments, name="customer_segments"),
    path("data-management/", views.data_management, name="data_management"),
    # Business-intelligence dashboard over the star-schema views
    path("bi-dashboard/", bi_views.bi_dashboard, name="bi_dashboard"),
    path("api/bi/kpis/", bi_views.api_bi_kpis, name="api_bi_kpis"),
    path("api/bi/product-drill/", bi_views.api_bi_product_drill, name="api_bi_product_drill"),
    path("api/bi/time-drill/", bi_views.api_bi_time_drill, name="api_bi_time_drill"),
    path("api/bi/stores/", bi_views.api_bi_stores, name="api_bi_stores"),
    path("api/bi/segments/", bi_views.api_bi_segments, name="api_bi_segments"),
    path("api/bi/basket-distribution/", bi_views.api_bi_basket_distribution, name="api_bi_basket_distribution"),
    path("api/bi/daypart/", bi_views.api_bi_daypart, name="api_bi_daypart"),
    path("api/bi/demographics/", bi_views.api_bi_demographics, name="api_bi_demographics"),
    path("api/bi/brand/", bi_views.api_bi_brand, name="api_bi_brand"),
    path("api/bi/top-products/", bi_views.api_bi_top_products, name="api_bi_top_products"),
    path("api/bi/discount-trend/", bi_views.api_bi_discount_trend, name="api_bi_discount_trend"),
    path("api/bi/insights/", bi_views.api_bi_insights, name="api_bi_insights"),
    # JSON/API endpoints used by front-end JS
    path("api/table/", views.api_get_table_data, name="api_get_table_data"),
    path("api/association-rules/insert/", views.api_insert_association_rule, name="api_insert_association_rule"),
    path("api/association-rules/department/", views.api_generate_department_rules, name="api_generate_department_rules"),
    path("api/association-rules/commodity/", views.api_generate_commodity_rules, name="api_generate_commodity_rules"),
    path("api/period-metrics/", views.api_get_period_metrics, name="api_get_period_metrics"),
    path("api/create/", views.api_create_record, name="api_create_record"),
    path("api/update/", views.api_update_record, name="api_update_record"),
    path("api/delete/", views.api_delete_record, name="api_delete_record"),
    path("api/export/", views.api_export_data, name="api_export_data"),
    path("api/schema/", views.api_table_schema, name="api_table_schema"),
    path("api/basket/", views.api_basket_details, name="api_basket_details"),
    path("api/product/", views.api_product_details, name="api_product_details"),
    path("api/household/", views.api_household_details, name="api_household_details"),
    path("api/segment/", views.api_rfm_details, name="api_rfm_details"),
    path("api/churn/", views.churn_api, name="churn_api"),
    path("api/churn/experiments/run/", views.run_churn_experiment, name="run_churn_experiment"),
    path("api/churn/experiments/<int:experiment_id>/details/", views.churn_experiment_details, name="churn_experiment_details"),
    path("api/churn/experiments/<int:experiment_id>/activate/", views.activate_churn_experiment, name="activate_churn_experiment"),
    path("api/churn/experiments/<int:experiment_id>/delete/", views.delete_churn_experiment, name="delete_churn_experiment"),
    path("api/churn/experiments/<int:experiment_id>/cache-history/", views.cache_churn_experiment_history, name="cache_churn_experiment_history"),
    path("api/differential/", views.api_differential_analysis, name="api_differential_analysis"),
    path("api/market-trends/", views.api_market_trends, name="api_market_trends"),
    path("api/regenerate-segments/", views.api_regenerate_segments, name="api_regenerate_segments"),
    # ML API endpoints
    path("api/ml/predictive/", views.predictive_analysis_api, name="predictive_analysis_api"),
    path("api/ml/predict-future/", views.predict_future_api, name="predict_future_api"),
    path("api/ml/train/", views.train_ml_models, name="train_ml_models"),
    path("api/ml/predictions/", views.get_predictions, name="get_predictions"),
    path("api/ml/recommendations/", views.get_recommendations, name="get_recommendations"),
    path("api/ml/performance/", views.get_model_performance, name="get_model_performance"),
    path("api/ml/training-status/", views.training_status_api, name="training_status_api"),
    path("api/ml/time-series/train/", views.train_product_time_series, name="train_product_time_series"),
    path("api/ml/time-series/forecast/", views.product_time_series_forecast, name="product_time_series_forecast"),
    path("api/ml/time-series/report/", views.product_time_series_report, name="product_time_series_report"),
]
