# Generated by Django 5.2.6 on 2025-09-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dunnhumby", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customersegment",
            name="churn_probability",
            field=models.FloatField(
                blank=True, default=0.0, help_text="churn probability score", null=True
            ),
        ),
    ]
