# Generated by Django 5.2.12 on 2026-08-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dunnhumby', '0003_churnexperiment_churncustomerscore'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='churncustomerscore',
            new_name='dunnhumby_c_experim_7067eb_idx',
            old_name='dunnhumby__experi_5be373_idx',
        ),
    ]
