# Generated by Django 5.2.12 on 2026-08-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dunnhumby', '0005_customer_history_snapshots'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerchurnprediction',
            new_name='dunnhumby_c_experim_2e793c_idx',
            old_name='dunnhumby_c_experim_91fdb1_idx',
        ),
        migrations.RenameIndex(
            model_name='customerstatesnapshot',
            new_name='dunnhumby_c_househo_9574be_idx',
            old_name='dunnhumby_c_househo_2182d3_idx',
        ),
    ]
