# Generated by Django 5.2.6 on 2025-09-16 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('household_key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('age_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('income_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('homeowner_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('hh_comp_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('household_size_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('kid_category_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'household',
            },
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='household',
            field=models.ForeignKey(blank=True, db_column='household_key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.household'),
        ),
    ]
