# Generated by Django 5.2.6 on 2026-08-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerrecommendationcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrecommendationcache',
            name='model_trained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
