# Generated by Django 5.2.6 on 2025-09-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_key', models.BigIntegerField(unique=True)),
                ('recommendations', models.JSONField(default=list)),
                ('alpha', models.FloatField(default=0.6)),
                ('rules_version', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Recommendation Cache',
                'verbose_name_plural': 'Customer Recommendation Caches',
                'db_table': 'customer_recommendation_cache',
            },
        ),
    ]
